name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Stage
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Repository Contents
        run: dir  # Lists the contents of the current directory for debugging

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'


      - name: Build Application
        run: msbuild ./SLDFA2Mehluli/SLDFA2Mehluli.sln /p:Configuration=Release


  test:
    name: Test Stage
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'  # Change to the appropriate version

      - name: Restore Dependencies
        run: dotnet restore SLDFA2Mehluli.sln

      - name: Run Unit Tests
        run: dotnet test SLDFA2Mehluli.sln --configuration Release

  deploy:
    name: Deploy Stage
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'  # Change to the appropriate version

      - name: Restore Dependencies
        run: dotnet restore SLDFA2Mehluli.sln

      - name: Publish Application
        run: dotnet publish SLDFA2Mehluli.sln --configuration Release --output ./publish

      - name: Deploy to Staging
        run: |
          # Add your deployment steps here
          # This could include copying files to a staging environment or using deployment tools

# You can add more stages as needed (e.g., integration tests, production deployment)
